### ISSUE TITLE
refine search output by distance from address

### ISSUE THREAD

**Issue by Ghlyon** [smartchicago/chicago-early-learning#453] opened 2014-08-12 20:02 UTC
We need to build (or reactivate) a feature that enables users to refine the output on the map by distance from the address or location entered. Example: limit search output by .5 mile, 1 mile, 2 miles, etc.

**Comment by srobbin** [comment] 2015-02-22 21:40
I'm having a hard time figure out how to do this. Do you think it would suffice if we put a scale indicator on the map? It would adjust the distance in miles as you zoomed in/out.

![screen shot 2015-02-22 at 3 38 42 pm](https://cloud.githubusercontent.com/assets/44719/6320653/1aaffcee-baa9-11e4-8295-2a35c3125ce6.png)

**Comment by smarziano** [comment] 2015-02-23 03:40
@srobbin,

Please correct me if I am wrong, but the user would be unable to limit search radius from homepage or search results page with this option.

Is the map center represented by the address searched and this icon?
![screen shot 2015-02-22 at 9 37 00 pm](https://cloud.githubusercontent.com/assets/5550969/6322483/f79e43aa-bada-11e4-8458-a252fc92f486.png)

This is an option, but my concern is that it won't be as useful because at this time when users search an address, and zoom out, the map is represented as the neighborhood outlines and does not show the early childhood locations.

![screen shot 2015-02-22 at 9 38 24 pm](https://cloud.githubusercontent.com/assets/5550969/6322496/2f802acc-badb-11e4-8e00-21f2affdfa4d.png)

**Comment by smarziano** [comment] 2015-02-25 18:44
@srobbin I received an update from our partners about this issue:
"I did speak to the team lead again. It was reiterated to me that when typing in a parents address the results that are returned are two broad. I understand that it is a matter of zooming into the map but the feedback I am getting is that is it is not user friendly."

I also learned that the search is done by address since most parents don't know what community area they live in.

My thought is that when they search by address, if they do not input the entire address they might be getting search results that are too broad or not as relevant.

Here is a test I did:
I searched "4000 N Broadway" and first got a result outside of Chicago. The drop-down did not appear with options as I was typing.
![image](https://cloud.githubusercontent.com/assets/5550969/6377605/f92c2a4a-bcea-11e4-8d03-36994b6811d7.png)

I then went back to the homepage and tried the same address "4000 N Broadway" and this time the drop-down did appear and provided options and upon clicking enter (without choosing that option specifically) I got to the address in Chicago I was looking for:
![image](https://cloud.githubusercontent.com/assets/5550969/6377650/32950b26-bceb-11e4-93ad-d3e4783c2756.png)

Therefore, the issue is more focused on more relevant search results vs. radius. I have a call set up for March 9, to learn more, but please inform me of the questions you might have.

**Comment by smarziano** [comment] 2015-02-25 18:47
In addition, they are interested in seeing a search like this:
http://cps.edu/Schools/Find_a_school/Pages/schoollocator.aspx

**Comment by smarziano** [comment] 2015-12-09 19:47
@theandrewbriggs We discussed this issue before and some options, but here are a couple of ways that we can handle this issue.

- Ideally, our partners wanted to see a search radius activated again. Therefore, on the homepage the user can choose a radius (0.5, 1, 2 miles) to see results within that view. This is harder task and might not work as well since search also accounts for centers & community areas, not only addresses.

- As seen in the above comment on Feb 25, our partners also said that the search results are too broad. Currently the search results view offers locations over 2 miles apart. We want to give users search results that are closer to their searched address. The default view should be zoomed in more. However, we should always try to provide 2-3 locations in view.

Let's think about some ways of handling this.

**Comment by theandrewbriggs** [comment] 2016-01-04 22:37
To start with, we're gonna start one-zoom level in and see how that produces results better.

**Comment by theandrewbriggs** [comment] 2016-01-20 20:45
I'm spinning the above comment off into it's own issue.

**Comment by smarziano** [comment] 2016-01-25 20:44
Closing this issue for now since we created issue #543 based on our partners' feedback and suggestions.

**Closed by smarziano** 2016-01-25 20:44 UTC
Labels: High Priority
